name: Test

on: workflow_dispatch
inputs:
  user_input:
    description: 'User Input:'
    required: true
    default: "14"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.5" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip

      - name: execute py script # run main.py
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          INPUT_STORE=${{ github.event.inputs.myInput }}
          result=$(python main.py)
          echo "script result is $(result)"
        id: step1

      - name: Set color
        id: random-color-generator
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT

      - name: Print output
        run: |
          echo "The count was ${{ steps.step1.outputs.AOBResult }}"
          echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      # work on python result
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
